<a href="https://colab.research.google.com/github/tuntunwinkic/ML_Specialization/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
X_train = np.array([[1, 1, 1],
[0, 0, 1],
 [0, 1, 0],
 [1, 0, 1],
 [1, 1, 1],
 [1, 1, 0],
 [0, 0, 0],
 [1, 1, 0],
 [0, 1, 0],
 [0, 1, 0]])

y_train = np.array([1, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [ ]:
X_train[0]

array([1, 1, 1])

In [ ]:
def entropy(p):
    if p == 0 or p == 1:
        return 0
    else:
        return -p * np.log2(p) - (1- p)*np.log2(1 - p)



In [ ]:
print(entropy(0.5))

1.0


In [ ]:
for i,x in enumerate(X_train):
  print(i)
  print(x)

0
[1 1 1]
1
[0 0 1]
2
[0 1 0]
3
[1 0 1]
4
[1 1 1]
5
[1 1 0]
6
[0 0 0]
7
[1 1 0]
8
[0 1 0]
9
[0 1 0]


In [ ]:
def split_indices(X, index_feature):
    """Given a dataset and a index feature, return two lists for the two split nodes, the left node has the animals that have
    that feature = 1 and the right node those that have the feature = 0
    index feature = 0 => ear shape
    index feature = 1 => face shape
    index feature = 2 => whiskers
    """
    left_indices = []
    right_indices = []
    for i,x in enumerate(X):  # i က index number, x က feature array
        if x[index_feature] == 1:  # index_feature 0 ထားတာက ပထမဆုံး index သည် ၁ ဖြစ်မဖြစ်စစ်
            left_indices.append(i)
        else:
            right_indices.append(i)
    return left_indices, right_indices

In [ ]:
split_indices(X_train, 0)

([0, 3, 4, 5, 7], [1, 2, 6, 8, 9])

In [ ]:
left_indices, right_indices = split_indices(X_train, 0)



In [ ]:
left_indices

[0, 3, 4, 5, 7]

In [ ]:
y_train[left_indices] # ytrain ရဲ့ left_indices နေရောတွေမှာ ကြောင်တွေ ရှိလား ခွေးတွေ ရှိလား ၁ ကြောင် ၀ ခွေး

array([1, 1, 0, 1])

In [ ]:
y_train[[0, 3, 4, 5, 7]]

array([1, 0, 1, 1, 1])

In [ ]:
def weighted_entropy(X,y,left_indices,right_indices):
    """
    This function takes the splitted dataset, the indices we chose to split and returns the weighted entropy.
    """
    w_left = len(left_indices)/len(X)
    w_right = len(right_indices)/len(X)
    p_left = sum(y[left_indices])/len(left_indices) #  ytrain ရဲ့ left_indices နေရောတွေမှာ ကြောင်တွေ ရှိလား ခွေးတွေ ရှိလား ၁ ကြောင် ၀ ခွေး
    p_right = sum(y[right_indices])/len(right_indices)

    weighted_entropy = w_left * entropy(p_left) + w_right * entropy(p_right)
    return weighted_entropy

In [ ]:
left_indices, right_indices = split_indices(X_train, 0)
weighted_entropy(X_train, y_train, left_indices, right_indices)

0.7219280948873623

In [ ]:
def information_gain(X, y, left_indices, right_indices):
    """
    Here, X has the elements in the node and y is theirs respectives classes
    """
    p_node = sum(y)/len(y)
    h_node = entropy(p_node)
    w_entropy = weighted_entropy(X,y,left_indices,right_indices)
    return h_node - w_entropy

In [ ]:
information_gain(X_train, y_train, left_indices, right_indices)

0.2780719051126377

In [ ]:
for i, feature_name in enumerate(['Ear Shape', 'Face Shape', 'Whiskers']):
    left_indices, right_indices = split_indices(X_train, i)
    i_gain = information_gain(X_train, y_train, left_indices, right_indices)
    print(f"Feature: {feature_name}, information gain if we split the root node using this feature: {i_gain:.2f}")


Feature: Ear Shape, information gain if we split the root node using this feature: 0.28
Feature: Face Shape, information gain if we split the root node using this feature: 0.03
Feature: Whiskers, information gain if we split the root node using this feature: 0.12
